# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftSHWB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'MJRefresh'


  # Pods for SwiftSHWB

  target 'SwiftSHWBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftSHWBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
